version: "3.1"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: apshuk17/movieclient
    expose:
      - "3000"
    ports:
      - "8080:3000"
    links:
      - server
    volumes:
      - "/app/node_modules"
      - "./client:/app"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: apshuk17/movieserver
    environment:
      PORT: 5000
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - "/app/node_modules"
      - "./server:/app"