version: "3.1"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: apshuk17/movieclient
    expose:
      - "3000"
    ports:
      - "8080:3000"
    links:
      - server
    volumes:
      - "/app/node_modules"
      - "./client:/app"
    depends_on: 
      - mongo
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: apshuk17/movieserver
    environment:
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=test
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - "/app/node_modules"
      - "./server:/app"
    depends_on: 
      - mongo

  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    expose:
      - "27017"

volumes:
  data-volume: